### ISSUE TITLE
TARGET_PREBUILT_RECOVERY_RAMDISK_CPIO again? 

### ISSUE THREAD

**Issue by Terminator-J** [crdroidandroid/android_build#28]
Hi there, yes at the end of the day this is an "I want to be able to inline TWRP for recovery on my device" discussion. 
Not sure if this has been had already and decided upon, but here goes.
On OnePlus 6/6T, you used to be able to set TARGET_PREBUILT_RECOVERY_RAMDISK_CPIO, which would get picked up by build/core/Makefile at https://github.com/crdroidandroid/android_build/blob/c8a65c92d087e9828e94373fcd188191243a757c/core/Makefile#L1913 and it would extract the contents of a prebuilt CPIO recovery image filesystem (like from the TWRP installer zip) from the device tree files into the appropriate output folder to get picked up & packaged into the recovery ramdisk. 
Looks like this was added by https://github.com/crdroidandroid/android_build/commit/f4ea93a106b95f09899df3ae7b8e3e42a7c25cee#diff-d486e601a844f08eaa052d963bedbdd8a7db76d664a5f44fe34bf4fd6db1064a
And of course, it doesn't actually work now. 
I'm wondering if this is still a good place to start, but figure out how to apply the magic (or, specifically, magisk) kernel hex patching and so forth that the TWRP installer utilizes as well... since obviously we can't execute arm64 elf binaries in the linux/darwin x86 build system. 
Looks like clues could be found in the for block of, for example, https://github.com/TeamWin/android_device_oneplus_fajita/blob/62c64e13a192a9037556f3902c6d3a3ad6f747ff/installer/META-INF/com/google/android/update-binary#L39 although that's device-specific and this would kind of require each device to have its own patching function defined in the device tree.

**Comment by gwolf2u** [comment]
this can't be done for now
we need to wait for TWRP with proper A11 support and see if can be done
current TWRP is not quite ready
